name: Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
      uses: docker://swift:latest
    - name: test AnyCodable package
      run: swift test