name: Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker
        uses: docker://swift:latest
        run: swift test
        